### PR TITLE
fix: update mime library method signature to 2.X

### PR DESCRIPTION
**Pull request by Lennart-J**
Due to this error unleash.start({import: {file: './some_file.yaml'}}) is currently not possible

Originally done here
https://github.com/Unleash/unleash/commit/c66545e11e08c90d47bfda0fe051dec03a7a40be

### CODE REVIEW

**Comment by ivarconr** [comment]
Thanks, I think we should consider a test for it as well. Are you up for that @Lennart-J ?

**Comment by Lennart-J** [comment]
Hi, I didn't setup the project locally, just trying to setup unleash in my infrastructure :)
Afraid I would only get to that by next weekend

**Comment by ivarconr** [comment]
I see the code no longer compiles. 

```bash
src/lib/services/state-util.ts:15:12 - error TS2339: Property 'getType' does not exist on type 'typeof import("/home/runner/work/unleash/unleash/node_modules/@types/mime/index")'.

15 ) => (mime.getType(file) === 'text/yaml' ? YAML.load(data) : JSON.parse(data));
```

Are you sure that its not an error on your side using an old "mime" library? Did you remember to run `yarn build` or `npm install` afterwards`?

**Comment by Lennart-J** [comment]
I'm using the helm chart / docker image, so I'm not doing any npm install myself.

The error occurs when starting the docker image, running unleash with a custom index.js entrypoint

unleash.start({
     import: {
       file: './some_file.yaml',
       keepExisting: false,
       dropBeforeImport: false,
     }
  });

ERROR] TypeError: mime.lookup is not a function
    at Object.parseFile (/unleash/node_modules/unleash-server/dist/lib/services/state-util.js:28:40)
    at /unleash/node_modules/unleash-server/dist/lib/services/state-service.js:27:42
    at async createApp (/unleash/node_modules/unleash-server/dist/lib/server-impl.js:94:9)
    at async Object.start (/unleash/node_modules/unleash-server/dist/lib/server-impl.js:138:21)

Just looked around a bit and thought this should be the easy fix

**Comment by Lennart-J** [comment]
While this is a separate issue, I tried the import/export APIs as an alternative today, and it also doesn't really work, since activation are left in a boken state when importing, making it unusable as well.
Is there some import/export that is working for you @ivarconr ?

**Comment by ivarconr** [comment]
> Just looked around a bit and thought this should be the easy fix

yes, this was actually a result of the types not being updated confusing typescript. Your change is the correct one.

**Comment by ivarconr** [comment]
> Is there some import/export that is working for you @ivarconr ?

yes, but i am curios on which versions you are exporting / importing from. We discovered a few inconsistencies when we worked on v4.2. We also added unit tests to import configuration from all recent minor version of Unleash. 

Maybe you can share some not working  on [slack](https://slack.unleash.run)?
